name: Sync Fork

on:
  schedule:
    - cron: '* 0/3 * * *' # every sixth hour
  workflow_dispatch:

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: TG908/fork-sync@v1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: sigp
          base: master
          head: master
      -
        name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update tags
        run: |
          git remote add upstream https://github.com/sigp/lighthouse.git
          git fetch upstream
          git pull
          git push --tags

